### ISSUE TITLE
关于使用MySQL存储的一点疑惑

### ISSUE THREAD

**Issue by biningo** [iambiglee/myMessageQueue#1]
作为存算分离架构的MQ，如果使用MySQL作为存储的话，性能可能会有瓶颈
想学习一下博主当初选MySQL存储是怎么个想法，学习学习

**Comment by iambiglee** [comment]
Hello Biningo
我选择 mysql主要是基于以下几点考虑
开发与维护成本：考虑到开发和维护一个分布式文件存储系统的复杂性和工作量，特别是在业余时间开发的情况下，这样做允许我将精力集中在功能上，而不是在底层存储技术上分散我们的注意力。

架构简化：通过使用MySQL，简化技术栈，减少系统的复杂性。这种简化可以让大家了解数据结构更加容易。同理我也避免了引入额外的服务发现和分布式一致性组件，如Dubbo、Zookeeper或Eureka，从而进一步降低了系统的复杂度。

运维和监控：许多团队已经拥有管理MySQL的经验和资源。利用这些现有的运维和监控能力，我可以确保数据库的高效运行，同时合理地利用资源。

性能考量：虽然像Kafka和RocketMQ这样的系统通过使用自研的文件存储系统来追求极致的性能，但对于绝大多数业务场景而言，MySQL的性能已经足够应对。99.99%的使用场景中，MySQL的性能不会成为瓶颈。

**Comment by biningo** [comment]
感谢回答！推荐一种现成MQ存储方案：https://github.com/openmessaging/dledger
